### ISSUE TITLE
[Angular 10] TypeError: jwt_decode__WEBPACK_IMPORTED_MODULE_3__ is not a function

### ISSUE THREAD

**Issue by cloakedch** [auth0/jwt-decode#102]
When using the module like so:

```ts
import * as jwt_decode from 'jwt-decode';

[...]

const decodedToken= jwt_decode(myToken);
```

then angular 10 will throw the following error:

`TypeError: jwt_decode__WEBPACK_IMPORTED_MODULE_3__ is not a function`

Note that the documented ES module import does not work:

`import jwt_decode from 'jwt-decode'`, as this will throw:

```
This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```

which is NOT the angular way of solving this issue.

**Comment by Sambego** [comment]
That error you're getting seems to be a problem with the TS type declaration which are not a part of this project. The types are a part of [this repository](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jwt-decode), feel free to create a pull-request to fix them and the maintainer will review them.

I will look into including type declarations into this project in the future.
