### ISSUE TITLE
Build output inconsistency makes it impossible to create TypeScript definitions

### ISSUE THREAD

**Issue by remcohaszing** [auth0/jwt-decode#103]
### Description

This is basically DefinitelyTyped/DefinitelyTyped#49112, but as an issue in this repository.

Because the `main` entry uses `module.exports = function jwtDecode() {}` to export the function, and the `module` entry uses `export default function jwtDecode() {}`, it’s impossible to create TypeScript definitions for version 3 of this library.

The CommonJS export should be typed as:

```ts
declare function jwtDecode();
export = jwtDecode;
```

The ESM export should be typed as:

```ts
export default function jwtDecode();
```

This has caused various issues reported here for people who don’t know how to use this library.

#90 #91 (comments) #96 #97 #102

#### Solution A: Omit ESM module

Removing the ESM module and `module` entry from `package.json` would leave the CJS export. This deoptimizes module bundling, but looks the prettiest in a NodeJS environment.

NodeJS usage:

```js
const jwtDecode = require('jwt-decode');
```

Module / TypeScript usage:

```ts
import * as jwtDecode from 'jwt-decode';
```

Type definition:

```ts
declare function jwtDecode();
export = jwtDecode;
```

#### Solution B: Use default key in CJS

Another solution is to favor ESM syntax and use `module.exports.default` for CJS.

NodeJS usage:

```js
const { default: jwtDecode } = require('jwt-decode');
```

Module / TypeScript usage:

```ts
import jwtDecode from 'jwt-decode';
```

Type Definition:

```ts
export default function jwtDecode();
```

#### Solution C: Use named exports (My personal favourite)

Named exports look good in both CJS and ESM.

NodeJS usage:

```js
const { jwtDecode } = require('jwt-decode');
```

Module / TypeScript usage:

```ts
import { jwtDecode } from 'jwt-decode';
```

Type Definition:

```ts
export function jwtDecode();
```

### Reproduction

N/A

### Environment

> Please provide the following:

- **Version of this library used:** 3.0.0
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:** TypeScript, `@types/jwt-decode`

**Comment by Blackglade** [comment]
Can confirm, just ran into this exact problem. What I am having a hard time understanding is why there are two different jwtDecode() functions exported?

**Comment by remcohaszing** [comment]
#### Solution D: Assign `exports.default` in the `cjs` output.

In [index.cjs.js](https://github.com/auth0/jwt-decode/blob/v3.0.0/lib/index.cjs.js), adding the following would also work:

```ts
wrapper.default = jwtDecode;
```

Type definition:

```ts
export default function jwtDecode();
```

This is the only non-breaking solution so far.

For example axios [does this as well](https://github.com/axios/axios/blob/v0.21.0/lib/axios.js#L53).

**Comment by glennreyes** [comment]
I posted https://github.com/auth0/jwt-decode/pull/105#issuecomment-720737355 that should be able to fix this issue.
