### ISSUE TITLE
Suggestion: Support generics

### ISSUE THREAD

**Issue by cloakedch** [auth0/jwt-decode#109]
It would be great if the function `jwtDecode` could be supplied with a generic type, so that it doesn't have to be cast.

Currently (unless I'm missing something here):

```ts
const myDecodedToken: MyTokenPayload = jwt_decode(tokenString) as MyTokenPayload;
```

By changing the typings from

```ts
export default function jwtDecode(token: string, options?: JwtDecodeOptions): unknown;
```

to

```ts
export default function jwtDecode<T>(token: string, options?: JwtDecodeOptions): T;
```

We could then write

```ts
const myDecodedToken = jwt_decode<MyTokenPayload>(tokenString);
```

or even

```ts
const myDecodedToken: MyTokenPayload = jwt_decode(tokenString);
```

Any comments?

**Comment by cloakedch** [comment]
We could probably also introduce a default, so there would be no breaking changes:

```ts
export default function jwtDecode<T = unknown>(token: string, options?: JwtDecodeOptions): T;
```

Defaults are supported since TypeScript 2.3

**Comment by remcohaszing** [comment]
There was some discussion about this in #105. Since this issue has already gotten quite a lot of upvotes in a small amount of time, I think this is what people want and the return type should be made generic.

**Comment by Sambego** [comment]
From `v3.1.2` onwards you can either specify the return type or use the default `unknown` type.

```typescript
import jwtDecode, { JwtPayload } from "jwt-decode";
const decoded = jwtDecode<JwtPayload>(token); // returns the JwtPayload also exported
```
or
```typescript
import jwtDecode from "jwt-decode";
const decoded = jwtDecode(token); // returns unknown
```
