### ISSUE TITLE
ES6 version

### ISSUE THREAD

**Issue by AlexKirilov** [auth0/jwt-decode#113]
Hello,

is it possible to be prepared an ES6 version? This will remove the angular warning message and it can decrease the bundle size
`WARNING in C:\****\****.service.ts depends on 'jwt-decode'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies`

Regards!

**Comment by AlexGuironnetRTE** [comment]
Hello,
I'd be interested too!
Thanks!

**Comment by Sambego** [comment]
The latest version has an ESM build included when you install it through NPM, have you updated the package to `v3.1.2` ?

https://github.com/auth0/jwt-decode/blob/a99d74a2e848b12a6a542f284dbf53ab83a5117a/package.json#L6

**Comment by AlexGuironnetRTE** [comment]
I just did and it works like a charm! Thanks a lot for the pointer!
