### ISSUE TITLE
Symbol "InvalidTokenError" is not exported when using jwt-decode.js standalone

### ISSUE THREAD

**Issue by marcodb26** [auth0/jwt-decode#114]
### Description

I'd like to verify the type of exception with something like this:

```
try {
  decodedJwt = jwt_decode(potentialJwt);
} catch(e) {
  if(!(e instanceof InvalidTokenError)) {
    throw e;
  }
}
```

However, the symbol InvalidTokenError is not exported. A workaround is:

```
if(e.__proto__.name != "InvalidTokenError") {
  [...]
}
```

but it's not ideal.

### Reproduction

Include the standalone jwt-decode.js in a web page.

### Environment

- **Version of this library used:** 2.2.0
- **Version of the platform or framework used, if applicable:** N/A
- **Other relevant versions (language, server software, OS, browser):** Using Chrome, "user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by salvattore001** [comment]
same here!
