### ISSUE TITLE
Angular 6 version

### ISSUE THREAD

**Issue by randym127** [auth0/jwt-decode#116]
Which version of the library is supported by Angular 6 and Typescript 2.9.2?

We setup Auth0 in a branch that was running Angular 5 without issue, but recently upgraded our Application to Angular 6 and now we are getting an error in this package.

ERROR in node_modules/jwt-decode/index.d.ts(22,39): error TS2304: Cannot find name 'unknown'.

The 'unknown' type is part of Typescript 3 I believe.  Just wondering what version we can downgrade to for Angular 6?  

p.s. It is weird that this worked in Angular 5 and the older Typescript and now doesn't in Typescript 2.9,2.  Oh well, thank you for any help and time.  Cheers

**Comment by randym127** [comment]
I just downgraded to 2.2, and that seems to work for now.  Sorry I should of just tried that before reaching out.  But maybe this will help someone.  Feel free to delete the issue.

**Comment by AmrAbdalrahman** [comment]
@randym127 thank you, your solution works with me.
