### ISSUE TITLE
Feature request: Verify token

### ISSUE THREAD

**Issue by jedd-ahyoung** [auth0/jwt-decode#12]
I think it would be worth it for this library to provide verification as well as the regular decode functionality. You wouldn't want to do this with symmetric key signing, but it'd work well with asymmetric auth.

I think you could probably pull the `verify` method from node-jsonwebtoken into this codebase without a lot of fuss. What do you guys think? For my use case, I'll need this and I"ll likely fork the library. I could submit a pull request.

**Comment by ajoslin** [comment]
I love the tinyness of this library right now. Verification of jwt definitely seems like a separate job from decoding.

**Comment by jedd-ahyoung** [comment]
Is the decoding portion of the library handled by a different library? JWS, I believe?

**Comment by jfromaniello** [comment]
@jedd-ahyoung No, it is handled here very simply this make the library very tiny and perfect for the browser. I agree with @ajoslin, the library ready has a name and I am not planning to change that.
It might be possible to use jsonwebtoken or jws in the browser with browser if but on my experience when browserify replaces crypto or even buffer you end up with a huge bundle.

jwt.io uses http://kjur.github.io/jsjws/, which is pure js and allow signing and checking signatures in the browser just fine.
