### ISSUE TITLE
Type for JwtPayload is missing claims

### ISSUE THREAD

**Issue by grempe** [auth0/jwt-decode#121]
The `JwtHeader` and `JwtPayload` typescript types are defined here:

https://github.com/auth0/jwt-decode/blob/master/index.d.ts#L12

`JwtHeader` is missing the `kid` claim which Auth0 provides in its JWT Access tokens.

`JwtPayload` is missing the following claims that Auth0 commonly provides.

* `azp` - The client ID of the Auth0 application
* `scope` - a space separated list of scopes
* `permissions` - a string or Array of strings

Adding these, and any others that Auth0 or other JWT creators commonly supports would make decoding when using Typescript a better developer experience.

![Screen Shot 2021-09-24 at 1 10 12 PM](https://user-images.githubusercontent.com/117/134715019-a4e1d866-f223-429c-b68f-9561b389cfca.png)

**Comment by grempe** [comment]
Ping. Don't love the auto-close policy for bugs that the team just hasn't commented on at all.

**Comment by stevehobbsdev** [comment]
Thanks for your patience here @grempe - this repo has now been taken over by a different team within Auth0 engineering and will focus some time in the short term to triage and progress outstanding issues like this one.

**Comment by frederikprijck** [comment]
As mentioned by @stevehobbsdev , thanks for the patience.
We are taking over this repository and I have been looking into this issue.

It's important to know that this library is not expected to be used solely with Auth0. Its vendor-agnostic and follows the JWT spec, without incorporating any vendor-specific implementations.

The JWT spec includes 7 claims: https://datatracker.ietf.org/doc/html/rfc7519, all of these are included in the JWTPayload.

![image](https://user-images.githubusercontent.com/2146903/157210228-1eade55d-364c-49f8-82ad-764043c39821.png)

We will be adding the `kid` claim to the JWTHeader, as we believe that would make sense.
But we can't be adding `scope`, `azp` and `permissions` as they are not defined in the JWT spec.

To solve this, I believe you want to use something along the lines of:

```
import jwt_decode from "jwt-decode";
interface Auth0JwtPayload extends JWTPayload {
  azp: string;
  scope: string;
  permissions: string[]
}

const decoded = jwt_decode<MyInterface>('TOKEN HERE');
```
