### ISSUE TITLE
Thoughts on adding a bin?

### ISSUE THREAD

**Issue by jrjohnson** [auth0/jwt-decode#129]
### Describe the problem you'd like to have solved

I'd like to be able to run `npx jwt-decode 'STRING'` and get an output similar to:

```
var decoded = jwt_decode(token);
console.log(decoded);
```

### Describe the ideal solution

Add a [bin](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#bin) entry to package.json and a small `cli` command to this library.

Eg:
```
//in package.json
{ "bin" : { "jwt-decode" : "./cli.js" } }
```

```
//cli.js
import jwt_decode from "../build/jwt-decode";
var decoded = jwt_decode(process.argv[2]);

console.log(decoded);
```

## Alternatives and current work-arounds

I could create and publish my own `jwt-decode-cli` to do this work. 
A more full featured CLI could be added to parse args with nice error messaging and respond to `npx jwt-decode --help` using something like [meow](https://github.com/sindresorhus/meow), but this would add dependencies that may be difficult to audit.

### Additional context

Happy to do a PR to add this if it's something you'd be up for merging.

**Comment by jrjohnson** [comment]
I see the mention of browser now, though I think calling this a library for reading tokens would be as accurate since it seems to run just fine in any node environment whereas the `node-jsonwebtoken` library does *way* more.  I'll go ahead and do my own npm package to accomplish this task.

Thanks,

**Comment by jfromaniello** [comment]
just in case this helps:

```bash
alias jwt-decode="jq -R 'split(\".\") | .[1] | @base64d | fromjson'"
```
