### ISSUE TITLE
xCode 7.0 Error in JWTDecode.swift

### ISSUE THREAD

**Issue by RoninSTi** [auth0/jwt-decode#13]
There is an error on line 108 in JWTDecode.swift after updating to XCode 7.0

<img width="1984" alt="screen shot 2015-09-18 at 1 51 44 pm" src="https://cloud.githubusercontent.com/assets/9053846/9966742/8ddad534-5e0c-11e5-801b-ad5f6ff446fa.png">

**Comment by eeschimosu** [comment]
+1

**Comment by jfromaniello** [comment]
I think you are looking at the wrong repository:

https://github.com/auth0/JWTDecode.swift

**Comment by eeschimosu** [comment]
Yes. Thanks!
