### ISSUE TITLE
jwt-decode does not work with requirejs

### ISSUE THREAD

**Issue by rlamorea** [auth0/jwt-decode#15]
I have attempted:

     require([ 'jwt-decode' ], function(jwt_decode) {
         var token = ...;
         var decoded = jwt_decode(token);
     });

I also attempted without assigning jwt_decode in the function (hoping for the global jwt_decode function to be available).

In both cases, `jwt_decode` is undefined, although the library is definitely being loaded.

I ended up working around this by just including the library directly before doing anything with requirejs.

**Comment by li-wu** [comment]
I have the same problem.

**Comment by jfromaniello** [comment]
Can you try with `require( [ 'jwt_decode' ...`?

It seems is defined with this name here:
https://github.com/auth0/jwt-decode/blob/master/standalone.js#L13

sorry for the late response

**Comment by rlamorea** [comment]
Finally got around to testing again.  I switched the require to 'jwt_decode', and that does seem to work.

Good enough.

**Comment by jfromaniello** [comment]
Glad to help!

**Comment by james-flume** [comment]
I'm getting jwt_decode undefined when I try to use require.js. I'm also getting jwt_decode undefined with a normal script include. I'm referencing the file jwt-decode.js in the /build folder.
