### ISSUE TITLE
Publish a named AMD

### ISSUE THREAD

**Issue by sandstrom** [auth0/jwt-decode#17]
This is a great lib, and I like that it's available via Bower.

One thing that would make it even better would be to publish a _named AMD_. They play well with ES6 modules and are used in e.g. ember-cli (the official tooling for Ember.js).

Here is an example of a library that exports a _plain amd_ and a _named-amd_ (for reference):
https://github.com/instructure/ic-ajax/tree/master/dist

More on AMD:
http://requirejs.org/docs/whyamd.html

**Comment by danconnell** [comment]
:+1: for this idea, as this package isn't easily to plug into an Ember-CLI project.

**Comment by jfromaniello** [comment]
Sorry for the delay, but isn't this already defining a named amd module here?

https://github.com/auth0/jwt-decode/blob/master/standalone.js#L13

**Comment by sandstrom** [comment]
@jfromaniello I recall trying to get it working as a named amd but could not. I think the issue may be around detecting `define`, but not 100% sure (it was a few months ago, cannot remember with precision).

**Comment by jfromaniello** [comment]
what should we do regarding this?

**Comment by Exelord** [comment]
Hey guys, I created a package for EmberJS developers.
https://github.com/Exelord/ember-jwt-decode

I think that will help you.
