### ISSUE TITLE
Consider dropping Universal Module Definition (UMD) bundle

### ISSUE THREAD

**Issue by jonkoops** [auth0/jwt-decode#180]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/jwt-decode#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/jwt-decode/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Since version 4 of this library is going to contain breaking changes (#175) to the Universal Module Definition (UMD) bundle, we might want to consider dropping it entirely. UMD was imagined when there were no module loaders on the web, which is no longer true now that we have [JavaScript modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules).

### Describe the ideal solution

Remove the UMD bundle and recommend users to use the official module system that JavaScript provides.

### Alternatives and current workarounds

Keep distributing the bundle, which likely nobody will use as it would require an explicit upgrade and migration steps.

### Additional context

See discussion under #174

**Comment by jonkoops** [comment]
@frederikprijck to get back to your earlier comment https://github.com/auth0/jwt-decode/pull/174#issuecomment-1658946985:

> I have a feeling you both have a strong reason to drop it, while i believe don't see the issue.

My main issue is long term maintenance, this code will be around for the entire 4.0 lifecycle, and it's an afterthought for most if not all tooling these days. Realistically those that are still using UMD are very unlikely to be actively maintaining projects, let alone upgrade and perform migrations (such as #175).

> My opinion is to keep it, even if there are alternative paths for those users to migrate. I want to avoid unneccesarily breaking users beyond things that are needed, especially given this lib is used extensively.

The thing is, if we are deciding to make these users perform the aforementioned migration steps, we might as well take the extra step and pull it entirely. Especially since this will only be used in legacy applications.

**Comment by jonkoops** [comment]
Update, we're looking to perhaps keep the UMD bundle backwards compatible (#181), so this might soon not be relevant anymore.

**Comment by frederikprijck** [comment]
Thanks. 

> Keep distributing the bundle, which likely nobody will use as it would require an explicit upgrade and migration steps.

We do support UMD in pretty much all of our JavaScript SDKs, and want to keep that if it doesn't cause any current issues.

> Especially since this will only be used in legacy applications.

Legacy applications shouldn't mean they are unable to use our SDK.
E.g. people might be using this with IE11. And even though this isn't something we support, or even recommend. I also believe there is no reason to break them more than necessary when keeping support around asks no effort and has no negative impact on any of our other users (if one of the latter two would be different, I would strongly opt to remove it).

**Comment by jonkoops** [comment]
Closing this for #181
