### ISSUE TITLE
Yarn installing jwt-decode causes nx Daemon to crash

### ISSUE THREAD

**Issue by YoungWoong-Cho** [auth0/jwt-decode#221]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/jwt-decode#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/jwt-decode/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

* macOS
* `"nx": "16.3.0"`

I currently have a `nx` workspace with node backends and typescript react frontend.

When I try to run the nx project using `nx:serve` after installing `jwt-decode` using `yarn add jwt-decode`, I get the following error:

```
>  NX   Nx Daemon was not able to compute the project graph.

   Log file with the error: /Users/.../node_modules/.cache/nx/d/daemon-error.log
   Please file an issue at https://github.com/nrwl/nx
   Nx Daemon is going to be disabled until you run "nx reset".
```

I have tried:
* Running `nx reset`
* Disabling daemon by using `export NX_DAEMON=false;`
* Try different version of `nx` (16.5.0)

None of the solutions above works. I would have to re-install every modules and install again without `jwt-decode` to make it work.

### Reproduction

1. `yarn add` nx 16.3.0 and `yarn add` jwt-decode
2. `yarn run ${your_package}:serve` 

### jwt-decode version

3.1.2

### Which browsers have you tested in?

Chrome

**Comment by jonkoops** [comment]
> `Log file with the error: /Users/.../node_modules/.cache/nx/d/daemon-error.log`

What is the output of this log?

**Comment by jonkoops** [comment]
I am unable to reproduce this issue with NX version `16.10.0` and Yarn using the latest stable of `jwt-decode`.

@YoungWoong-Cho you'll have to provide a [minimal and reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). If it's not possible to reproduce this issue, then it cannot be fixed, and it will have to be closed.

I see you are using different commands to 'serve' your code, but without any background information on what that actually runs there is little we can do here.

Could you perhaps create a new NX project with **only** the code required to reproduce this issue and share it on GitHub? Also please check the beta version of `jwt-decode` as @frederikprijck recommended, as this might resolve the problem.

**Comment by jonkoops** [comment]
@frederikprijck I propose we close this issue due to lack of response. I am also skeptical this has anything to do with `jwt-decode` itself.
