### ISSUE TITLE
InvalidTokenError: Invalid token specified: Unexpected number at position 0

### ISSUE THREAD

**Issue by ejdisney22** [auth0/jwt-decode#223]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/jwt-decode#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/jwt-decode/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am able to decode my token using 
var token = jwt_decode(token)
But when I run 
var token_header = jwt_decode(token, { header: true })
I am getting the error 
InvalidTokenError: Invalid token specified: Unexpected number at position 0
I have seen other InvalidTokenErrors in your docs but none are for the specific error that I am seeing

### Reproduction

1. Generate JWT Token
2. Decode token using jwt_decode(token) to check the payloads validity
3. Decode token header using jwt_decode(token, { header: true })
4. See error InvalidTokenError: Invalid token specified: Unexpected number at position 0 in the logs

### jwt-decode version

3.1.2

### Which browsers have you tested in?

Chrome

**Comment by jonkoops** [comment]
Are you sure the token you have generated is not invalid? I just tried to reproduce this (which is hard to do without the original token), but things seem to [work as expected](https://stackblitz.com/edit/js-6fr2ud?devToolsHeight=100&file=index.js).

**Comment by ejdisney22** [comment]
Figure out that I was not supposed to included the word BEARER in the token variable I was trying to decode, thanks for your help jonkoops

**Comment by jonkoops** [comment]
No problem!
