### ISSUE TITLE
On NPM page, git links are outdated

### ISSUE THREAD

**Issue by toomastahves** [auth0/jwt-decode#23]
Hey, on NPM page Github repo links are outdated:
https://www.npmjs.com/package/jwt-decode
```
github.com/auth0/jwt-decode.js
https://github.com/auth0/jwt-decode.js/blob/master/auth0.com
https://github.com/auth0/jwt-decode.js/blob/master/LICENSE.txt
```

**Comment by wjbryant** [comment]
The repository URL in package.json should be changed from `git://github.com/auth0/jwt-decode.js` to `git://github.com/auth0/jwt-decode.git`.

**Comment by wjbryant** [comment]
Actually, it looks like there is already a pull request for this (#20).

**Comment by jfromaniello** [comment]
Thanks for reporting this. I already merged the PR and released a patch.

**Comment by wjbryant** [comment]
Awesome! That means #16 can be closed as well.
