### ISSUE TITLE
missing: https://unpkg.com/jwt-decode@4.0.0/build/jwt-decode.js 

### ISSUE THREAD

**Issue by ddoherty** [auth0/jwt-decode#235]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/jwt-decode#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/jwt-decode/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

https://unpkg.com/jwt-decode@4.0.0/build/jwt-decode.js

is missing:

Cannot find "/build/jwt-decode.js" in jwt-decode@4.0.0

Is there another source available?

### Reproduction

<script src="https://unpkg.com/jwt-decode/build/jwt-decode.js"></script>

does not work.

### jwt-decode version

4.0.0

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
Where did u get this URL from?

It should either be https://unpkg.com/jwt-decode@4.0.0/build/esm/index.js or https://unpkg.com/jwt-decode@4.0.0/build/cjs/index.js

**Comment by ddoherty** [comment]
OK. Thanks!

**Comment by jonkoops** [comment]
This file no longer exists, the directory structure has changed in version v4. We now offer two separate entry points, one for environments using [JavaScript modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules), and one for [CommonJS](https://nodejs.org/api/modules.html#modules-commonjs-modules) environments. The UMD bundle is no longer supported.

- JavaScript — [`build/esm/index.js`](https://unpkg.com/browse/jwt-decode@4.0.0/build/esm/index.js)
- CommonJS — [`build/cjs/index.js`](https://unpkg.com/browse/jwt-decode@4.0.0/build/cjs/index.js)

Like @frederikprijck mentioned, you should always include a version number (preferably the whole version) for the package to make sure you don't get any breaking changes by accident. But you should also remove the path from the URL, as this can be changed any time in the future, and might not be considered a breaking change by package authors.

Instead, you should rely on unpkg to find the right path for you. By default it will resolve the CommonJS version, but you can opt-in to the ECMAScript version by adding the [`?module ](https://www.unpkg.com/#query-params) query parameter to the URL. For example:

- https://unpkg.com/jwt-decode@4.0.0 will resolve to https://unpkg.com/jwt-decode@4.0.0/build/cjs/index.js
- https://unpkg.com/jwt-decode@4.0.0?module will resolve to https://unpkg.com/jwt-decode@4.0.0/build/esm/index.js?module

If you want to avoid a redirect, you can always specify the full path and version number, as breaking changes to the path will never occur if you provide a fixed version (the file will always be the same).

You can then `import` the ECMAScript module version from your script by adding a [type="module"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#module) attribute to your script tag:

```html
<script type="module">
  import { jwtDecode } from "https://unpkg.com/jwt-decode@4.0.0?module";
</script>
```

Or alternatively, if you need to use this import in multiple places, and you want a more human-readable name you can use an [import map](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap):

```html
<script type="importmap">
  {
    "imports": {
      "jwt-decode": "https://unpkg.com/jwt-decode@4.0.0?module"
    }
  }
</script>
```

> Note: This script tag must be placed before the first `<script type="module">` tag in the document (preferably in the `<head>`)

With the above example, you can then import the code using a [bare import](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap#bare_modules) specifier on any page:

```html
<script type="module">
  import { jwtDecode } from "jwt-decode";
</script>
```
