### ISSUE TITLE
No Support for React Native & Expo

### ISSUE THREAD

**Issue by DeveloperAspire** [auth0/jwt-decode#248]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/jwt-decode#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/jwt-decode/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am trying to decode a jwt token sent from the backend in a React Native expo app and it keeps throwing an error but sure works in a web environment. I expected this to work but it keeps throwing the error "InvalidTokenError: Invalid token specified: invalid base64 for part #2 (Property 'atob' doesn't exist)]"

I have tried all the best I can to solve this. Please help.

### Reproduction

1. Create a react native expo applicatio
2. Use the package in the react native expo application to decode any jwt token at all.
3. Print the error to the console.

### jwt-decode version

4.0.0

### Which browsers have you tested in?

Other

**Comment by jonkoops** [comment]
Since this is a duplicate, shall we close this issue @frederikprijck?
