### ISSUE TITLE
Compatibility Issue with Node.js 16.18.1 on Expo Application Servers

### ISSUE THREAD

**Issue by Quingsley** [auth0/jwt-decode#250]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/jwt-decode#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/jwt-decode/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am  attempting to use the jwt-decode package within my Expo dev client project. However, during the installation of project dependencies, I encounter an error message that indicates a compatibility issue with Node.js. The error message looks like this:

>error jwt-decode@4.0.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.18.1"

>error Found incompatible module.

>info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

>Error: Unknown error. See logs of the Install dependencies build phase for more information

### Reproduction

1.  Create an expo app 
2.  Add as part of your dependency jwt-decode version 3.1.2
3.  Try to build the project on EAS

### My package.json file
{
  "name": "rnt-ui",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "lcl": "set APP_ENV=lcl && expo start --dev-client",
    "dev": "set APP_ENV=dev && expo start --dev-client",
    "stg": "set APP_ENV=stg && expo start --dev-client",
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@config-plugins/react-native-blob-util": "^6.0.0",
    "@config-plugins/react-native-pdf": "^6.0.0",
    "@gorhom/bottom-sheet": "^4.5.1",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-firebase/app": "^18.6.1",
    "@react-native-firebase/messaging": "^18.6.1",
    "@react-navigation/bottom-tabs": "^6.5.10",
    "@react-navigation/drawer": "^6.6.5",
    "@react-navigation/native": "^6.1.8",
    "@react-navigation/native-stack": "^6.9.14",
    "@reduxjs/toolkit": "^1.9.6",
    "async-mutex": "^0.4.0",
    "expo": "~49.0.13",
    "expo-application": "~5.3.0",
    "expo-constants": "^14.4.2",
    "expo-dev-client": "~2.4.11",
    "expo-document-picker": "~11.5.4",
    "expo-font": "~11.4.0",
    "expo-image-picker": "~14.3.2",
    "expo-linking": "~5.0.2",
    "expo-print": "~12.4.2",
    "expo-sharing": "~11.5.0",
    "expo-status-bar": "~1.6.0",
    "expo-web-browser": "~12.3.2",
    "fbjs": "^3.0.5",
    "jwt-decode": "^3.1.2",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-blob-util": "^0.19.1",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-international-phone-number": "^0.6.0",
    "react-native-localize": "^3.0.2",
    "react-native-onboarding-swiper": "^1.2.0",
    "react-native-pager-view": "6.2.0",
    "react-native-paper": "^5.10.6",
    "react-native-paper-dates": "^0.19.8",
    "react-native-paper-dropdown": "^1.0.7",
    "react-native-pdf": "^6.7.1",
    "react-native-ratings": "^8.1.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-uuid": "^2.0.1",
    "react-redux": "^8.1.3",
    "redux-persist": "^6.0.0",
    "socket.io-client": "^4.7.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "@types/react-native-onboarding-swiper": "^1.1.5",
    "typescript": "^5.1.3"
  },
  "private": true,
  "prettier": {
    "arrowParens": "avoid",
    "singleQuote": false,
    "printWidth": 150
  }
}

### jwt-decode version

3.1.2

### Which browsers have you tested in?

Other

**Comment by jonkoops** [comment]
As outlined in the [release notes](https://github.com/auth0/jwt-decode/releases/tag/v4.0.0), support for Node.js 16 has been dropped. The minimal version of Node.js now supported is version 18 and up, this is the same range [actively supported](https://nodejs.org/en/about/previous-releases#previous-releases) by the Node.js team.

I would recommend that you upgrade to a more recent version of Node.js like version 18 or 20, which are both LTS versions.

**Comment by Quingsley** [comment]
Yeah I fixed it by explicitly stating the node version to be used by EAS in my eas.json file
