### ISSUE TITLE
React native decode 

### ISSUE THREAD

**Issue by dazx606** [auth0/jwt-decode#260]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/jwt-decode#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/jwt-decode/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

this is the answer when I try to decode a token using the version 4: 
[InvalidTokenError: Invalid token specified: invalid base64 for part #2 (Property 'atob' doesn't exist)]
I had to install version 3.1.2.

import jwtDecode  from "jwt-decode";   //import v3
import {jwtDecode}  from "jwt-decode";   //import v4

const decodedToken:JwtPayload = jwtDecode(token); 

token is the same in both version.

### Reproduction

import {jwtDecode}  from "jwt-decode";   

const decodedToken:JwtPayload = jwtDecode(token); 

### Additional context

I'm using react native

### jwt-decode version

4.0.0

### Which browsers have you tested in?

Other

**Comment by frederikprijck** [comment]
Duplicate, see https://github.com/auth0/jwt-decode/issues/248#issuecomment-1787429549
