### ISSUE TITLE
InvalidTokenError

### ISSUE THREAD

**Issue by nadeemGroupIn** [auth0/jwt-decode#268]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/jwt-decode#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/jwt-decode/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

While doing apple sign in in iOS facing the following issue after authentication while trying to decode data that time facing this issue. 

error', [InvalidTokenError: Invalid token specified: invalid base64 for part #2 (Can't find variable: atob)]

### Reproduction

In our react native app After using @invertase/react-native-apple-authentication to social media apple login in our app when trying to decode idenityToken by using jwt-decode plugin facing above issue

### jwt-decode version

4.0.0

### Which browsers have you tested in?

Other

**Comment by jonkoops** [comment]
Duplicate of #241

**Comment by nadeemGroupIn** [comment]
Issue resolved.
just i downgraded the plugin jwt-decode version from 4.0.0 to 3.1.2

**Comment by jonkoops** [comment]
You can still continue to use the new version, you'll just have to [load a polyfill](https://github.com/auth0/jwt-decode#polyfilling-atob).
