### ISSUE TITLE
Can't install anymore, npm base64 seems to be obsolete now

### ISSUE THREAD

**Issue by rvetere** [auth0/jwt-decode#27]
jwt-decode has it's own dependency to npm base64 -and with latest node.js you can't build the base64 packages anymore. It generates a flood of syntax errors in the base64 package codebase and it seems that this is caused by breaking changes in V8.

Now quite interesting, as stated on the base64 package page (https://github.com/pkrumins/node-base64)

> Update: this module may no longer be necessary as nodejs includes its own
base64 encoding/decoding functions.

Is an update of jwt-decode planned somehow? I think best would be to change to native base64 functionality and remove the dependency fully. I didn't knew about those changes and googled around a bit, seems that basic Buffer objects can handle that already pretty well, or do i miss something that would break the current "base64_url_decode" implementation of the jwt-decode package?

http://stackoverflow.com/a/6182519/1214508

what i try for the moment is to create my own common class which tries to replicate the functionality of jwt-decode with basic base64 impl of node.js

**Comment by jfromaniello** [comment]
Node.js has been always able to encode/decode base64.

New browsers can do it as well. The reason I used this library was to support old browsers

**Comment by rvetere** [comment]
Ok so i helped out myself... With a handy little code snippet as found on scotch.io (and on many other places):

`
// Create Base64 Object
var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(e){var t="";var n,r,i,s,o,u,a;var f=0;e=Base64._utf8_encode(e);while(f<e.length){n=e.charCodeAt(f++);r=e.charCodeAt(f++);i=e.charCodeAt(f++);s=n>>2;o=(n&3)<<4|r>>4;u=(r&15)<<2|i>>6;a=i&63;if(isNaN(r)){u=a=64}else if(isNaN(i)){a=64}t=t+this._keyStr.charAt(s)+this._keyStr.charAt(o)+this._keyStr.charAt(u)+this._keyStr.charAt(a)}return t},decode:function(e){var t="";var n,r,i;var s,o,u,a;var f=0;e=e.replace(/[^A-Za-z0-9+/=]/g,"");while(f<e.length){s=this._keyStr.indexOf(e.charAt(f++));o=this._keyStr.indexOf(e.charAt(f++));u=this._keyStr.indexOf(e.charAt(f++));a=this._keyStr.indexOf(e.charAt(f++));n=s<<2|o>>4;r=(o&15)<<4|u>>2;i=(u&3)<<6|a;t=t+String.fromCharCode(n);if(u!=64){t=t+String.fromCharCode(r)}if(a!=64){t=t+String.fromCharCode(i)}}t=Base64._utf8_decode(t);return t},_utf8_encode:function(e){e=e.replace(/rn/g,"n");var t="";for(var n=0;n<e.length;n++){var r=e.charCodeAt(n);if(r<128){t+=String.fromCharCode(r)}else if(r>127&&r<2048){t+=String.fromCharCode(r>>6|192);t+=String.fromCharCode(r&63|128)}else{t+=String.fromCharCode(r>>12|224);t+=String.fromCharCode(r>>6&63|128);t+=String.fromCharCode(r&63|128)}}return t},_utf8_decode:function(e){var t="";var n=0;var r=c1=c2=0;while(n<e.length){r=e.charCodeAt(n);if(r<128){t+=String.fromCharCode(r);n++}else if(r>191&&r<224){c2=e.charCodeAt(n+1);t+=String.fromCharCode((r&31)<<6|c2&63);n+=2}else{c2=e.charCodeAt(n+1);c3=e.charCodeAt(n+2);t+=String.fromCharCode((r&15)<<12|(c2&63)<<6|c3&63);n+=3}}return t}}

// Define the string
var string = 'Hello World!';

// Encode the String
var encodedString = Base64.encode(string);
console.log(encodedString); // Outputs: "SGVsbG8gV29ybGQh"

// Decode the String
var decodedString = Base64.decode(encodedString);
console.log(decodedString); // Outputs: "Hello World!"
`

Create your own little class with this implementation for example and i was able to remove "jwt-decode" completely from my project and my auth0 demo impl finally works now :)

**Comment by jfromaniello** [comment]
@rvetere Yes, I will take care of this. node.js always supported base64 encoding/decoding, the reason I used a pure js module was to support old browsers.

**Comment by rvetere** [comment]
Yes i've understood this point already on the first reading.. it's just not really helpful information when your stuck with your setup just because of an un-installable package ;) So, what will the fix will be..? Will the auth0 package soon be updated to latest packages or.. you still waiting until angular2 becomes more "final"..? I mean, the auth0 demo project is still include beta.0.. two weeks ago beta.8 was relased and 1 day ago, beta.9 came out... it is actually extremely outdated..

And so far as i can see - the part where the decode is used most, it is unfortunately on the client.. you will never have nodejs there to support your base64 ;)

I just wanted to post my solution here so others may find help by going trough this thread.

**Comment by jfromaniello** [comment]
Sorry I didn't see my previous response hahha.

I just tried using Buffer directly and it works in the browser, but the problem is that the size increases by a factor of 10x... 


I will test this one:

https://github.com/davidchambers/Base64.js

**Comment by jfromaniello** [comment]
Done! v2.0.0 doesn't have any dependency.
