### ISSUE TITLE
Export base64UrlDecode function

### ISSUE THREAD

**Issue by mathiasklassen** [auth0/jwt-decode#346]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/jwt-decode#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/jwt-decode/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

First of all, I appreciate the excellent work on this library. We use it in our Angular applications for decoding JWTs.

In our current project, we have encountered a requirement to decode a registration token that is base64Url-encoded but not a JWT. As the base64UrlDecode function is not part of the public API, we need to implement it ourselves. This adds unnecessary redundancy and complexity to our codebase.

### Describe the ideal solution

We would like the base64UrlDecode function to be exposed in the public API. This would prevent the need to reimplement this functionality ourselves or resort to other libraries for this purpose.

### Alternatives and current workarounds

Currently, we have to implement the base64UrlDecode function ourselves or use a different library to achieve the same functionality.

### Additional context

If the team is interested or does not have the time to implement it, I am happy to provide a pull request with the necessary changes.

**Comment by jonkoops** [comment]
Seems fine to me to expose this as a public API, although it would need to be properly documented of course.

**Comment by frederikprijck** [comment]
This is a library to decode JWT's, not do general base64 (url) decoding. Once we add the `base64UrlDecode` function to the public API, we may end up with questions about exposing a base64encode variant as well etc, and before we know it we have to start supporting more use-cases than intended.

Adding your own `base64UrlDecode` in your own application should be relatively straightforward to implement.
