### ISSUE TITLE
In TypeScript when jwtDecode(token), the return is a JwtPayload Interface, hence the expiration time must to be expires instead exp

### ISSUE THREAD

**Issue by GuiMunizPB** [auth0/jwt-decode#355]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/jwt-decode#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/jwt-decode/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In typescript when:
const decoded = jwtDecode(token);
console.log(decoded);
{id:, expires: }
decode.exp return undefined 
the correct is decode.expires
You have to change the JwtPayload Interface to:
expires: number

### Reproduction

const decoded = jwtDecode(token);
console.log(decoded);

'''
{id: , expires:}

### jwt-decode version

4.0.0

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
I can't reproduce this. I tried andd I get `exp`, not `expires`. Can you elaborate how this can be reproduced?
