### ISSUE TITLE
include type definition

### ISSUE THREAD

**Issue by PatrickJS** [auth0/jwt-decode#36]
can you include a type definition file? probably starting off with something like
`lib/index.d.ts`

``` typescript
function jwtDecode(token: string): any;
namespace jwtDecode {}
export = jwtDecode;
```

`package.json`

``` json
{
  "typings": "lib/index.d.ts"
}
```

related https://github.com/AngularClass/angular2-webpack-starter/issues/755#issuecomment-230537444

**Comment by mbeauchamp7** [comment]
```typings search jwt-decode``` It's there

**Comment by jfromaniello** [comment]
I am willing to do this but I am not familiar with those tools, can you send me a PR?

(sorry for the delay)

**Comment by hanssens** [comment]
As also mentioned in the PR #42, I tend to agree with @mbeauchamp7 here; the typings are already available through:

```
# see also https://www.npmjs.com/package/@types/jwt-decode
npm install --save-dev @types/jwt-decode
```

Having it as part of the jwt-decode repo makes sense only if it is actively supported. Otherwise, I'd gladly trust the DefinitelyTyped version.
