### ISSUE TITLE
Webpack AMD build missing - jwt-decode not working with angular 2

### ISSUE THREAD

**Issue by manuelfink** [auth0/jwt-decode#43]
Tried to load jwt-decode in an angular 2 project however it always returns jwt-decode is not a module. Can you please add a webpack build?

install in ng2 cli project with npm install jwt_decode. Then load in module through_

```
import {jwt_decode} from "jwt_decode";
```

results in error:

```
Uncaught Error: Cannot find module "jwt_decode"
```

For now, I'm using the following script instead:

```
wt_decode (token) {
  var base64Url = token.split('.')[1];
  var base64 = base64Url.replace('-', '+').replace('_', '/');
  return JSON.parse(window.atob(base64));
};
```

**Comment by manuelfink** [comment]
I guess #17 should solve this issue too

**Comment by jfromaniello** [comment]
Can you try this?

~~~
import jwt_decode from "jwt_decode";
~~~

**Comment by rossholdway** [comment]
@jfromaniello That doesn't work for me (importing into Angular 2 with webpack). Using `import * as jwtDecode from "jwt-decode";` or `import jwt_decode from "jwt-decode";` will work though.

**Comment by karolmie1** [comment]
Add this to vendor:
import 'jwt-decode'

This to your typings:
declare module "jwt-decode" {
  function decode(token: string): any;
  namespace decode {}  // notice how we have to create a namespace that is equal to the function we're assigning the export to
  export = decode;
}


And this to your file: 
import * as jwt_decode from 'jwt-decode';

let decoded = jwt_decode(token);

**Comment by Kerollmops** [comment]
```js
import jwt_decode from "jwt-decode"
```
Be carreful the package name use a dash(`-`) not an underscore(`_`).

**Comment by DesHorsley** [comment]
I had to import it with `import * as jwtDecode from 'jwt-decode';` to get it working.
