### ISSUE TITLE
deos it work with react native ?

### ISSUE THREAD

**Issue by azamkth** [auth0/jwt-decode#49]

**Comment by rohit-ravikoti** [comment]
Looks like it does. It's being used with exponent here: https://github.com/graphcool-examples/expo-auth0-example/blob/master/exponent-auth0/main.js

**Comment by azamkth** [comment]
got error : Unable to resolve module jwt-decode. 
could you tell me how to configure this module with react native. i just run command npm install wt-decode and try to use like import jwtDecoder from 'jwt-decode'.

**Comment by rohit-ravikoti** [comment]
I think you need to do "npm install --save jwt-decode"

**Comment by azamkth** [comment]
thanks a lot :) problem has been fixed
