### ISSUE TITLE
Is jwt-decode still being actively maintained?

### ISSUE THREAD

**Issue by weblancaster** [auth0/jwt-decode#50]
Before committing/start using `jwt-decode` I just want to know still actively maintained.

Thanks for the great work.

**Comment by unicodeveloper** [comment]
Yes it is actively maintained. Go ahead and use it @weblancaster

**Comment by weblancaster** [comment]
@unicodeveloper looks like it is stale, where did you get that info? Would be nice to know from the maintainers/authors.

**Comment by hanssens** [comment]
@weblancaster I'm not an author, but the most recent release dates from 20 Mar - see also [all releases](https://github.com/auth0/jwt-decode/releases).
