### ISSUE TITLE
How to use it in node typescript applicaiton

### ISSUE THREAD

**Issue by yhjhoo** [auth0/jwt-decode#52]
what should I do after the following

var jwtDecode = require('jwt-decode');

I am very new to typescript and node

**Comment by DavidRutqvist** [comment]
I use it as such:
`import * as jwtDecode from "jwt-decode";`
and then e.g.
`if (this.token && (jwtDecode(this.token).exp >= Math.floor(Date.now() / 1000)))`

**Comment by DevanB** [comment]
@ignatzami This is happening to me as well. Curious if this library is:

1. Maintained still.
2. If not, what is a viable alternative to check the `exp` of a JWT.

I would assume Auth0 would maintain this, but 🤷‍♂️

**Comment by RiJung** [comment]
this works for me

```typescript
import JwtDecode from 'jwt-decode';

export function checkExpired() {
    const token = 'INSERT YOUR TOKEN HERE';

    interface TokenDto {
      foo: string;
      exp: number;
      iat: number;
    }

    interface TokenHeaderDto {
      typ: string;
      alg: string;
    }

    const decodedTokenPayloadOld = JwtDecode(token);
    const decodedTokenPayload = JwtDecode<TokenDto>(token);
    const decodedTokenHeaderOld = JwtDecode(token, { header: true });
    const decodedTokenHeader = JwtDecode<TokenHeaderDto>(token, { header: true });
    console.log('decodedTokenPayloadOld :', decodedTokenPayloadOld);
    console.log('decodedTokenPayload :', decodedTokenPayload);
    console.log('decodedTokenHeader :', decodedTokenHeader);
    console.log('decodedTokenHeaderOld :', decodedTokenHeaderOld);
}
```

**Comment by engpakravan** [comment]
Hi everyone i have problem when using jwt-decode package
when i use this package and implement my project i taked a bug names : 
`
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
`
so i tryed again but i know this is actualy for this package , no one have a solution for me ?
