### ISSUE TITLE
why isn't this library listed in he jwt web page library list https://jwt.io/#libraries-io?

### ISSUE THREAD

**Issue by Masber** [auth0/jwt-decode#59]

**Comment by yordis** [comment]
Because those are the implementation of JWT tokens,

this package the only thing it does it take a token and give you the metadata you could call it. Does not performance any encryption or decryption.

**Comment by Jaikant** [comment]
Wish this was listed at jwt.io, would have saved me an hour evaluating other things. I simply needed a decode.

**Comment by mpoisot** [comment]
I too was hoping to find a simple decoder library on jwt.io. I knew something must exist so I googled deeper, and found this. I think it should be listed there.
