### ISSUE TITLE
jwt is not decoding in angular 5

### ISSUE THREAD

**Issue by sayjavajava** [auth0/jwt-decode#60]
I have tried to install Jwt libraries but does not worked and i got news that is deprecated in latest angular release . :). I also tried [https://stackoverflow.com/questions/41818822/how-to-import-the-jwt-decode-type-definition-into-typescript-ionic-2](this) solution but failed .

I am using interceptor too and HttpClient also .means that new stuff working fine . 

but there is bug to decode jwt token and unable to install jwt libraries.

**Comment by AlexGeb** [comment]
Using 
`import * as decode from 'jwt-decode';` 
and then 
`const token = localStorage.getItem('token');
const tokenPayload = decode(token);` 
in my roleGuard in Angular 5 is working fine for me.

**Comment by maxtacco** [comment]
This worked for me: 
```javascript
import {default as decode} from 'jwt-decode';
```

**Comment by nkengasongatem** [comment]
Thank you guys, you made my day!

**Comment by andrefelipeml** [comment]
Thank you, this worked for me!

**Comment by FranckTONYA** [comment]
Merci!! Ca fonctionne a merveille!!
