### ISSUE TITLE
Token decode error

### ISSUE THREAD

**Issue by andrewlphilpott** [auth0/jwt-decode#61]
Some of our users have randomly been getting errors like and `Invalid token specified: e is undefined` thrown when their token is decoded. The odd thing is, I've checked all of their tokens and they all look fine. Does anybody know where I should start looking to figure out what the issue might be here?

For what it's worth, I'm logging out the token before I run it through `jwt_decode()` and all of our logs get recorded so I know that the token is there and that it's a valid token. Also, I _think_ this has only ever come up in Firefox.

**Comment by lipidity** [comment]
Same issue. No problems in Chromium, token not being parsed properly in Firefox

**Comment by xinghengwang** [comment]
yeah, I getting this issue also. in the node in the backend. 
I used jwt.io to decode it, it is fine. 
but using jwtDecode. I get 'Invalid token specified: Unexpected token è in JSON at position 0'

**Comment by xinghengwang** [comment]
It is not in the docs, but looking a the code. Sometimes you need to set the header option to true, depends on your token format. 

decode(token, {  header: true });

**Comment by andrewlphilpott** [comment]
In my situation it ended up being a weird edge case where users were attempting to access our app without a token. For some reason in Firefox the token was coming through as `'undefined'` rather than `undefined` and the conditional that I was doing before trying to decode tokens was only checking against `undefined`.
