### ISSUE TITLE
Reference error: jwt_decode is not defined (Mozilla Firefox)

### ISSUE THREAD

**Issue by davidtadic** [auth0/jwt-decode#63]
Does anyone know how to deal with this. I am using jwt_decode script for decoding jwt token. It works well in Chrome and Edge but I got this error in Firefox: ReferenceError: jwt_decode is not defined.

**Comment by sdmiller7** [comment]
I am seeing this error as well. Only in firefox. 

InvalidTokenError: Invalid token specified: str is undefined.

Anyone have a solution or work around?

**Comment by harshan89** [comment]
router.post('/reset_password', (req, res) => {
	const { password, token } = req.body.data;
	jwt.verify(token, process.env.JWT_WEB_SECRET, (err, decoded) => {
		if(err){
			res.status(401).json({errors: "Invalid token"})
		}
		else{
			res.json({});
			User.findOne({ _id: decoded._id }).then(user => {
				if(user) {
					user.setPassword(password);
					user.save().then(() => res.json({}));
				} else {
					res.status(400).json({ errors: { global : "Invalid token" }})
					}
			})
		}
	});
});


This works fine mate!
