### ISSUE TITLE
JWT InvalidTokenError: Invalid token specified

### ISSUE THREAD

**Issue by janajay** [auth0/jwt-decode#65]
InvalidTokenError: Invalid token specified
when logout i am clearing the local storage.

**Comment by janajay** [comment]
In react i am storing the token in the local storage and clearing when logging out. At that time i getting this issue 
InvalidTokenError: Invalid token specified

**Comment by goodok21** [comment]
the same issue in rotten tomatoes clone

**Comment by Steven-Harris** [comment]
Same.  I tried wrapping it in a try/catch and it didn't help

**Comment by AchrafBn** [comment]
Try this statement
```
if (!localStorage.getItem("jwtToken")) {
  //your code
}
```
it's works for me

**Comment by Leeds-eBooks** [comment]
Is this a duplicate of #61?

**Comment by john-pondr** [comment]
@Leeds-eBooks, I think it is different than [#61](https://github.com/auth0/jwt-decode/issues/61). Using the example code from [expo](https://github.com/expo/auth0-example), it throws this error in React Native.
```
Possible Unhandled Promise Rejection (id:0):
[InvalidTokenError: Invalid token specified]
```
And this is the returned Json:
```json
Object {
  "errorCode": undefined,
  "params": Object {
    "access_token": "FRHy4SaU3l4Wno2-5d8NJjxNhvsfLKEb",
    "exp://localhost:19000/--/expo-auth-session": "",
    "expires_in": "7200",
    "scope": "openid",
    "token_type": "Bearer",
  },
  "type": "success",
  "url": "exp://localhost:19000/--/expo-auth-session#access_token=FRHy4SaU3l4Wno2-5d8NJjxNhvsfLKEb&scope=openid&expires_in=7200&token_type=Bearer",
}
```

**Comment by testica** [comment]
@JoanDelilahPepin you can wrap this in a try-catch
``` js
  try {
    const data = decode(token);
    // valid token format
  } catch(error) {
    // invalid token format
  }

**Comment by xinghengwang** [comment]
It is not in the docs, but looking a the code. Sometimes you need to set the header option to true. 

Try: 
 
decode(token, {  header: true });

**Comment by julia30040** [comment]
I had this problem, too. I think parameter cannoot be null or undefined. Maybe you should check token is exist before decode. Like this:
```
import jwtDecode from 'jwt-decode'; 

if (token) {
  jwtDecode(token);
  ...
}

**Comment by ranjiit12** [comment]
`const jwtToken = localStorage.getItem("jwtToken");

if (jwtToken !== "undefined") {
  // Set auth token header auth
  setAuthToken(jwtToken);
  // Decode token and get user info and exp

}`
This worked for me. Initially I if statement was checking for
`if ( localStorage.getItem("jwtToken")) {your code}`
But it gave this replace token error when I updated password through react app.

**Comment by QfeetFlipStudios** [comment]
Hi, Anyone here knows how to use jwt-decode in react native?

**Comment by pankajm** [comment]
> I had this problem, too. I think parameter cannot be null or undefined. Maybe you should check token is exist before decode. Like this:
> 
> ```
> import jwtDecode from 'jwt-decode'; 
> 
> if (token) {
>   jwtDecode(token);
>   ...
> }
> ```

You should wrap up call to jwt-decode in try-catch block. Null or undefined argument to jwt-decode throws exception.

**Comment by dresean** [comment]
> @john-pondr you can wrap this in a try-catch
> 
> ```js
>   try {
>     const data = decode(token);
>     // valid token format
>   } catch(error) {
>     // invalid token format
>   }
> ```

bro you are a saint, I added this to my router to redirect on error and it worked like a charm. 👍🏾👍🏾👍🏾

**Comment by jasonk** [comment]
Looking at [the code](https://github.com/auth0/jwt-decode/blob/910b79f8862dead864a957576913aadb10cb696a/lib/index.js#L12) there are two conditions where you can get this error.  If the error message you get is just `Invalid token specified` it means the token wasn't a string.  If it says `Invalid token specified: <some other error message>` it means that error was thrown by either the base64 decoder or by `JSON.parse`.

**Comment by Thomasosho** [comment]
If you've decoded your token before just get to declare state and export it.
JWT_decode usually give this error when you decode the token multiple times.

**Comment by JBeanny** [comment]
I wanna get {email,name} from react-oauth/google and someone said we can get those by decoding the access_token of the oauth's response but end up getting "Invalid token specified" is there a way to fix this ?

**Comment by huynhdev24** [comment]
Best practices!

Clear localStorage and login App again!

![image](https://user-images.githubusercontent.com/124909303/232278634-bc9ac888-61e6-4272-9b07-57661826c065.png)

![image](https://user-images.githubusercontent.com/124909303/232278680-221701b6-e77f-45f0-bc3a-79f16ab8cff6.png)
