### ISSUE TITLE
Invalid token specified: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by alamothe** [auth0/jwt-decode#69]
I'm getting this error:
```
Invalid token specified: Cannot read property 'replace' of undefined
```

I'm using latest Create-React-App and Chrome browser. Please help

**Comment by alamothe** [comment]
It looks like its coming from https://github.com/auth0/jwt-decode/blob/master/lib/base64_url_decode.js#L4

**Comment by alamothe** [comment]
My bad :-( works as expected

**Comment by Srija-t2s** [comment]
But still I am getting this error

**Comment by alamothe** [comment]
Most likely you're passing an invalid token e.g. does not have two dots. The error could be improved
