### ISSUE TITLE
Broken using require('jwt-decode')

### ISSUE THREAD

**Issue by cyphercodes96** [auth0/jwt-decode#70]
lines 131-132-133-134
        const token = this.getJWTFromCookies();
        console.log(token);
        const jwtDecode = require('jwt-decode');
        const decoded = jwtDecode(token);

Traceback:

core.js:1671 ERROR Error: Uncaught (in promise): InvalidTokenError: Invalid token specified: Cannot read property 'replace' of undefined
InvalidTokenError
    at Object../node_modules/jwt-decode/lib/index.js (index.js:9)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/_services/authentication.service.ts (appointments.service.ts:39)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/appointments/update-appointment/update-appointment.component.ts (main.js:11191)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/app.module.ts (app.config.ts:8)
    at __webpack_require__ (bootstrap:76)
    at Object../src/main.ts (environment.ts:8)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/jwt-decode/lib/index.js (index.js:9)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/_services/authentication.service.ts (appointments.service.ts:39)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/appointments/update-appointment/update-appointment.component.ts (main.js:11191)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/app.module.ts (app.config.ts:8)
    at __webpack_require__ (bootstrap:76)
    at Object../src/main.ts (environment.ts:8)
    at __webpack_require__ (bootstrap:76)
    at resolvePromise (zone.js:814)
    at new ZoneAwarePromise (zone.js:894)
    at AuthenticationService.push../src/app/_services/authentication.service.ts.AuthenticationService.resolveRouting (authentication.service.ts:96)
    at authentication.service.ts:70
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:3825)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at zone.js:872
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
defaultErrorLogger @ core.js:1671
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:1717
next @ core.js:4320
schedulerFn @ core.js:3556
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:195
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:133
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:3540
(anonymous) @ core.js:3847
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:3784
onHandleError @ core.js:3847
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:392
push../node_modules/zone.js/dist/zone.js.Zone.runGuarded @ zone.js:154
_loop_1 @ zone.js:677
api.microtaskDrainDone @ zone.js:686
drainMicroTaskQueue @ zone.js:602
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
error (async)
customScheduleGlobal @ zone.js:1666
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:297
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:401
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleEventTask @ zone.js:258
(anonymous) @ zone.js:1831
(anonymous) @ http.js:1628
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe @ Observable.js:42
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:28
(anonymous) @ subscribeTo.js:21
subscribeToResult @ subscribeToResult.js:6
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._innerSub @ mergeMap.js:70
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext @ mergeMap.js:67
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next @ mergeMap.js:50
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
(anonymous) @ scalar.js:5
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe @ Observable.js:42
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:28
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call @ mergeMap.js:28
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:23
push../node_modules/rxjs/_esm5/internal/operators/filter.js.FilterOperator.call @ filter.js:15
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:23
push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call @ map.js:18
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:23
push../src/app/_services/authentication.service.ts.AuthenticationService.tokenConfiguration @ authentication.service.ts:64
push../src/app/_services/authentication.service.ts.AuthenticationService.login @ authentication.service.ts:59
push../src/app/auth/login/login.component.ts.LoginComponent.onSubmit @ login.component.ts:62
(anonymous) @ LoginComponent.html:9
handleEvent @ core.js:10259
callWithDebugContext @ core.js:11352
debugHandleEvent @ core.js:11055
dispatchEvent @ core.js:7718
(anonymous) @ core.js:9198
schedulerFn @ core.js:3568
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:195
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:133
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:3540
push../node_modules/@angular/forms/fesm5/forms.js.NgForm.onSubmit @ forms.js:3801
(anonymous) @ LoginComponent.html:8
handleEvent @ core.js:10259
callWithDebugContext @ core.js:11352
debugHandleEvent @ core.js:11055
dispatchEvent @ core.js:7718
(anonymous) @ core.js:8162
(anonymous) @ platform-browser.js:995
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:3816
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566

This broke yesterday

Can i get any help ASAP please?!

**Comment by lhminh167** [comment]
This thread solve the problem.
https://stackoverflow.com/questions/43886878/auth0-and-vue-error-in-render-function-invalidtokenerror-invalid-token-speci

**Comment by juank2808** [comment]
**Uncaught jwt-decode.esm.js:62** 
I don't understand what happend with this, can you help me please?
