### ISSUE TITLE
 Invalid token specified: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by aminsource** [auth0/jwt-decode#72]
### I get Invalid token specified: Cannot read property 'replace' of undefined:
```
Object.<anonymous> ../node_modules/jwt-decode/lib/index.js 9:0
Showing original source content from sourcemap
'use strict';
 var base64_url_decode = require('./base64_url_decode');
 function InvalidTokenError(message) {
  this.message = message;
}
 InvalidTokenError.prototype = new Error();
InvalidTokenError.prototype.name = 'InvalidTokenError';
 
module.exports = function(token, options) {
    if (typeof token !== 'string') {
      throw new InvalidTokenError('Invalid token specified');
    }
````
Can i get any help ASAP please?!

**Comment by atbmatt** [comment]
Having the exact same problem...

**Comment by atbmatt** [comment]
I was having this issue when using jwtDecode with a token issued from our Auth0 tenant.

Ensure your "audience" option in Auth0 exists and is correct. If it is not, you get back a token in the incorrect format.

**Comment by aminsource** [comment]
### I use jwtDecode for dispatch token to redux store as bellow:
```javascript
store.dispatch(loginUserSuccess(jwtDecode(Auth.getToken())));
```
#### and I use HS256

**Comment by ekofi** [comment]
Same problem here.

**Comment by atbmatt** [comment]
@aminsource Are you using Auth0 lock in your front end application? If so, what configuration options are you passing in when you initialize the lock component?

**Comment by lhminh167** [comment]
This thread solved the problem.
https://stackoverflow.com/questions/43886878/auth0-and-vue-error-in-render-function-invalidtokenerror-invalid-token-speci

**Comment by Gloryofthe80s** [comment]
In my case, I'm attempting to protect the client-side app against "corrupt" cookies (tokens that aren't in JWT format) in the event a user messes with their cookies. In the moment I'm decoding, if the token can't be parsed, the error thrown breaks the app, despite my attempt to catch.

```
export const isAccessTokenExpired = (): boolean => {
  if (!isAccessTokenSet()) {
    // if it doesn't exist, we'll also consider it expired
    return true;
  }

  // ensure it's actually JWT format
  try {
    jwt_decode(getAccessToken());
  } catch (error) {
    console.log('👾 invalid token format', error);
    return true;
  }

  const token = jwt_decode(getAccessToken());
  const { exp } = token;
  return Math.round(Date.now() / 1000) >= exp ? true : false;
};
```

Upon attempting to decode a non-JWT format value, the catch triggers, but the error still shows as Uncaught and breaks runtime:
```
👾 invalid token format InvalidTokenError {message: "Invalid token specified: Cannot read property 'replace' of undefined"}
InvalidTokenError {message: "Invalid token specified: Cannot read property 'replace' of undefined"}
message: "Invalid token specified: Cannot read property 'replace' of undefined"
```

**Comment by jyoti739** [comment]
I had same problem as well, If you are login to the App and you did play with token in backend(postman). then token mismatch might happen so you take recent token from postman and add it to the localstorage in the browser, which was in undefined.

**Comment by jtan4nih** [comment]
Is this going to be any fix for this? My error -

   "Invalid token specified: Cannot read property 'replace' of undefined" }
{ InvalidTokenError
    at Object.<anonymous> (c:\Users\w\strapi-deliveroo\frontend\node_modules\jwt-decode\lib\index.js:9:31)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.jwt-decode (c:\Users\w\strapi-deliveroo\frontend\.next\server\static\development\pages\index.js:836:18)
    at __webpack_require__ (c:\Users\w\strapi-deliveroo\frontend\.next\server\static\development\pages\index.js:23:31)
    at Module../lib/auth.js (c:\Users\w\strapi-deliveroo\frontend\.next\server\static\development\pages\index.js:503:68)
    at __webpack_require__ (c:\Users\w\strapi-deliveroo\frontend\.next\server\static\development\pages\index.js:23:31)
    at Module../hocs/defaultPage.js (c:\Users\w\strapi-deliveroo\frontend\.next\server\static\development\pages\index.js:356:67)
    at __webpack_require__ (c:\Users\w\strapi-deliveroo\frontend\.next\server\static\development\pages\index.js:23:31)
    at Module../pages/index.js (c:\Users\w\strapi-deliveroo\frontend\.next\server\static\development\pages\index.js:644:75)
    at __webpack_require__ (c:\Users\w\strapi-deliveroo\frontend\.next\server\static\development\pages\index.js:23:31)
  message:

**Comment by jpbamberg1993** [comment]
I'm only getting this error in safari, chrome an FF work

**Comment by skhetarpaul** [comment]
I feel it is only happening because token is set to undefined. Either clear out that token from inspect menu and refresh your application. It may work then.

**Comment by Sambego** [comment]
Hey friends,

I've been trying to reproduce all of the errors mentioned above. When using the `decode` function, make sure:
- The token is not undefined
- The token is a valid JSON Web Token,
- You remove the bearer authentication type, as this is not part of the token but indicates the authentication scheme
- The token header and payload are valid base64 encoded, this means the token can only contain these characters:  `a–z`, `A–Z`, `0–9`, and `-_.`
- When using a try/catch block to catch the invalid token error, make sure you're not trying to decode the token or header somewhere else in your code, as the error will only be caught in the try/catch block.

**Comment by Gurminder-Kaler** [comment]
In order re view the page without error goto inspect element of browser and find APPLICATIONS tab just beside the tabs like Elements, Console.
Find Local Storage there.
And Clear by right clicking
![redux](https://user-images.githubusercontent.com/18589457/120913125-48a23380-c6b2-11eb-85fc-cc80e32e21f2.PNG)

**Comment by bruno88cabral** [comment]
Hey, I can reproduce this error when I do automated tests with cypress, is anyone else going through this?

**Comment by ederuiter** [comment]
For future reference: this error occurs when the token does not adhere to the expected format of a jwt token

For example I ran into this in unit tests where the token was mocked with something like "FAKE_TOKEN"
Currently this lib assumes a valid syntax for the token meaning the token must include a single dot (.) and the part after the dot must be a valid base64 encode otherwise you'd get these errors.

Adding a check on undefined in base64_url_decode would solve this and could give developers a good clue to what is going wrong.

For now I replaced my `FAKE_TOKEN` with `FAKE.eyJmYWtlIjogdHJ1ZX0=` which causes the JwtDecode to succeed
