### ISSUE TITLE
QUESTION: Does this work with React-Native 

### ISSUE THREAD

**Issue by AlexMachin1997** [auth0/jwt-decode#75]
Hi,

This is not an issue but a query. Does JWT-decode work with React-Native? I'm building an app with authentication and this library keeps getting recommended by other developers, but I'm unsure if it works with React-Native.

Would appreciate any input 

Thanks,

Alex

**Comment by j-monteiro** [comment]
Hi, 

It works. The only problem I currently have is with naming conventions imposed by eslint, the only way I was able to import it was like **import jwt_decode from 'jwt-decode'** and eslint imposes that the identifier jwt_token to be written in camel case (jwtDecode).

**Comment by howardwu1** [comment]
I was able to circumvent the eslint issue by doing import { jwt_decode as jwtDecode } from 'jwt-decode' and then replace all jwt_decode with jwtDecode and it worked. Hope that helps!
