### ISSUE TITLE
Unable to use jwt-decode with typescript project

### ISSUE THREAD

**Issue by rahulbhooteshwar** [auth0/jwt-decode#82]
### Description
I am trying to use jwt-decode in a **typescript** project i.e. Stencil Project & it is throwing following error:

```
import * as jwt_decode from 'jwt-decode';
.
.
.
let token = "........";
let decoded = jwt_decode(token);
```
> This expression is not callable.Type '{ default: <TTokenDto>(token: string, options?: Options) => TTokenDto;
>            }' has no call signatures.

### Reproduction
* install jwt-decode in any typescript project
   * npm install --save @types/jwt-decode
   * npm install --save jwt-decode
* import it in your code & use
```
import * as jwt_decode from 'jwt-decode';
.
.
.
let token = "........";
let decoded = jwt_decode(token);
```
* build project

> Please provide the following:

- **Version of this library used:** ^2.2.0
- **Version of the platform or framework used, if applicable:** stencil - ^1.3.3 , typescript - 3.7.2

**Comment by yeuem1vannam** [comment]
You can import the `jwt_decode` directly
```typescript
import jwt_decode from 'jwt-decode';

let token = "........";
let decoded = jwt_decode(token);
```

**Comment by Widcket** [comment]
Hi @rahulbhooteshwar, [here's an example Typescript project](https://codesandbox.io/s/jwt-decode-typescript-8lzzb) with `jwt-decode`.

**Comment by showduhtung** [comment]
> Hi @rahulbhooteshwar, [here's an example Typescript project](https://codesandbox.io/s/jwt-decode-typescript-8lzzb) with `jwt-decode`.

I tried this but vscode gave me an error saying 'This expression is not callable'

**Comment by davevanhoorn** [comment]
> I tried this but vscode gave me an error saying 'This expression is not callable'

@showduhtung I'm getting the same error 'This expression is not callable', so I use it like this and it's working for me. I don't get why I have to pass the payload myself though.

    import jwt_decode, { JwtPayload } from 'jwt-decode'

    const decodedToken = jwt_decode<JwtPayload>(token)

**Comment by fabramosdev** [comment]
I resolved this issue as follows:

**import jwt_decode, { JwtPayload } from 'jwt-decode';**

**const decoded = jwt_decode<JwtPayload>(token || '') || null;**

console.log(decoded); // {id: "601872b3eee5d0001c1cdcb2", iat: 1613648982, exp: 1613735382}

**Comment by RituparnaA2Z-CM** [comment]
Hi @fabramosdev  Thanks , it really works but could not fetch that value from this object and get the separate value. Could you tell me how to do that. Thanks in advance.

**Comment by fabramosdev** [comment]
> Hi @fabramosdev Thanks , it really works but could not fetch that value from this object and get the separate value. Could you tell me how to do that. Thanks in advance.

Hi, in case you want to get each value separately inside the object?

If I understand your question correctly, because of the typescript you can call "decoded.iat", "decoded.exp" or even in this case shown the "decoded.id".

Hope this helps

**Comment by RituparnaA2Z-CM** [comment]
Hi @fabramosdev  , yes I tried that, but it is not working in .ts file but in .js . Is there any way to fetch the values in typescript. I am getting compile time error while fetching the value using {decoded.iat}.

**Comment by vskowronsky** [comment]
Oh, I have the same problem as @RituparnaA2Z-CM!
My code is 
`import jwt_decode, {JwtPayload} from 'jwt-decode';
getCustomerId(){
    let token =  this.getToken();
    let decoded = jwt_decode<JwtPayload>(token ||'') || null;
    console.log('Token aus getCustomerId: ' + decoded)
  }`

But in the console I just get an object
console.log from Browser: Token aus getCustomerId: [object Object]

**Comment by RituparnaA2Z-CM** [comment]
@vskowronsky hey I have solved the issue. Just type cast it with your object model. Let say, 
export class Model {
field1: string;
field2:string;
field3:string;
}

import the model from package path;
import jwt_decode, { JwtPayload } from 'jwt-decode';
const decoded = jwt_decode<Model >(token || '') || null;

console.log(" fetching field 1 -----", decoded.field1);
console.log(" fetching field 2 -----", decoded.field2);
console.log(" fetching field 3 -----", decoded.field3);

**Comment by vskowronsky** [comment]
Thank you very much for answering :-) 

I did try your approach but it did not work for me.

This is my code, that worked for me in the end:

`getCustomerId(){`
    `let decoded = jwt_decode<JwtPayload>(this.getToken());`
`    console.log('Token aus getCustomerId: ' + decoded['data'].id)`
    `return decoded['data'].id`
 ` }`

data is the name of the payload field in my token. I had to reference it in square brackets and then look for the id.

Hope that is helpfull for any one else as well. It is always good to have alternatives.

**Comment by RituparnaA2Z-CM** [comment]
@vskowronsky  thank you so much for another option. Yes, it is very much true to have second options in case but sad to know that my approach did not work for you :(. Anyways happy to know that you fixed it.

**Comment by derfl007** [comment]
I came across the same "This expression is not callable" problem, and specifying the type did not solve the issue.
I was however able to fix it by calling `jwtDecode.default<JwtPayload>(...)` instead. Not sure why that's a thing, but I thought I'd share in case anyone has the same problem!

**Comment by cristobal** [comment]
> I came across the same "This expression is not callable" problem, and specifying the type did not solve the issue. I was however able to fix it by calling `jwtDecode.default<JwtPayload>(...)` instead. Not sure why that's a thing, but I thought I'd share in case anyone has the same problem!

When in a standard ESM module it's not a problem:
![Screenshot 2023-05-04 at 22 16 04](https://user-images.githubusercontent.com/155505/236319341-8dd3ee5c-e3b7-4710-bb95-a1199e239d6b.png)

However from TypeScript:
![Screenshot 2023-05-04 at 22 17 32](https://user-images.githubusercontent.com/155505/236319609-74b833f2-5cfb-4cf0-bcdb-1015a3d80829.png)

TypeScript sees it as module import not a function per se, and this happens whenever [`moduleResolution`](https://www.typescriptlang.org/tsconfig#moduleResolution) is set to NodeNext. I think this a bug per se with TypeScript since Node ESM resolution is inferring types correctly.

However a middleground approach until fixed could be to change the exports to e.g.:

```js
export function decode(token, options) {
}

export default decode;
```

The in the TypeScript defintions defined the following:

```ts
...
export function decode<T = unknown>(
  token: string,
  options?: JwtDecodeOptions
): T

export default decode;
```

Then TS would resolve the module correctly.
![Screenshot 2023-05-04 at 22 24 25](https://user-images.githubusercontent.com/155505/236321003-2fd37d7c-de91-450e-8afb-ce5c31adb146.png)

And it would still be backwards compatible.

**Comment by janusqa** [comment]
Hi I am having this issue. 
"moduleresolution": "nodenext"

**Comment by fredbanda** [comment]
If some of you are still trying to figure it out try "import {jwtDecode} from 'jwt-decode'

**Comment by michelsampil** [comment]
⚠️ It's a named export so it must be imported this way:

import { jwtDecode } from "jwt-decode"

![image](https://github.com/user-attachments/assets/201240c7-a045-400c-95ef-d8af4d48f3ae)
