### ISSUE TITLE
Should describe try, catch in document(Readme.md).

### ISSUE THREAD

**Issue by qkreltms** [auth0/jwt-decode#83]
### Describe the problem you'd like to have solved
I got an throw error, but it was hard to find it where it occurs.
It was the ```jwt_decode``` due to ```{message: "Invalid token specified"}```
I had not known that it throws an error.

### Describe the ideal solution
It would be happy wrapping jwt_decode(...) try {  } catch (error) { ... } for new users who would look up readme.md.

**Comment by Widcket** [comment]
Thanks for bringing this up! I added a mention to the error in the README.
