### ISSUE TITLE
Cannot find module 'jwt-decode' in angular 2 project

### ISSUE THREAD

**Issue by akvaliya** [auth0/jwt-decode#88]
### Description
Trying to use in angular 2 project. It gives error  `Cannot find module 'jwt-decode'`

### Reproduction
`import * as jwtDecode from "jwt-decode";`
Also tried `import * as jwt_decode from "jwt-decode";`

### Environment

![](https://content.screencast.com/users/jalpeshrajani/folders/Jing/media/d8093585-2a8a-4d6d-b109-1423d368a8be/2020-05-13_1255.png)
`

**Comment by athisun** [comment]
It sounds like you haven't installed the package into your project.

Run `npm install jwt_decode` in the project's root directory. For improved Typescript support, install the accompanying types package as a development dependency with `npm install --save-dev @types/jwt_decode`.

Then you can use `import * as jwt_decode from "jwt-decode";` to import the module.

**Comment by RachiLam** [comment]
From the [npm page](https://www.npmjs.com/package/jwt-decode) 

> Can also be used with browserify or webpack by doing npm install jwt-decode and requiring:
> var jwtDecode = require('jwt-decode');

So wouldn't it be `import jwt_decode from 'jwt-decode'`? You want to import the default export. Also the variable name doesn't matter.
