### ISSUE TITLE
Warning when using with Angular 10

### ISSUE THREAD

**Issue by dmytro-gokun** [auth0/jwt-decode#90]
WARNING in src\app\auth\state\auth.token.ts depends on 'jwt-decode'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Are there any plans to update to ESM modules?

**Comment by Michael-Ziluck** [comment]
Big +1 from me. I did not realize this was a problem before Angular started warning me about it. Would be nice to get a reply from the maintainers of this project if possible.

**Comment by bboehm86** [comment]
I don't thinkt that this is a big problem for the optimization since this lib is so small. But you could use just the helper service from `@auth0/angular-jwt` package if you need the decode an want the warning to be gone: https://github.com/auth0/angular2-jwt#usage-standalone

**Comment by Sambego** [comment]
I've published a new (beta) version `3.0.0-beta.0` which adds ESM support. That should fix those Angular 10 warnings. Could you test if this works well for you?

Pull request: #92

**Comment by anders8** [comment]
>Angular 10 warnings. Could you test if this works well for you?

I tested this with Angular 10.0.6. I was using v2.2.0 and had the warning referenced. I switched to v3.0.0-beta.2 (by manually editing my package.json and then running npm update jwt-decode) and the error is no longer present. Ahh, AND yes, my code still worked with no changes on my end. Thanks @Sambego ! 👍👍👍

**Comment by dmytro-gokun** [comment]
@Sambego Are there any plans to release this in the near future?

**Comment by Sambego** [comment]
The latest stable release `v3.0.0` should fix the CommonJS and AMD warning.

**Comment by anders8** [comment]
Thanks for your time on this @Sambego , much appreciated!

**Comment by shivraj-bhagat** [comment]
Warning: /node_modules/@auth0/angular-jwt/__ivy_ngcc__/fesm2015/auth0-angular-jwt.js depends on 'url'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

I am getting this warning with "@auth0/angular-jwt": "4.1.2".
