### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by bearkfear** [auth0/jwt-decode#91]
### Describe the problem you'd like to have solved

TypeScript integration, must have a d.ts file for projects made in TypeScript work fine!

![image](https://user-images.githubusercontent.com/33099123/87879099-f0d9db80-c9be-11ea-85f7-a7684fa3ea83.png)

**Comment by AlBlanc** [comment]
Install npm package "@types/jwt-decode" as dev depedency

**Comment by bastienmoulia** [comment]
Not working for V3.0.0 currently.
And it would be better to have it in the official lib.

**Comment by teledemic** [comment]
After 3.0.0, @types/jwt-decode no longer matches the new import signature and is not currently a solution
