### ISSUE TITLE
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode

### ISSUE THREAD

**Issue by AlBlanc** [auth0/jwt-decode#93]
### Description
I am just trying to decode a token in a React project.

### Reproduction

```
   import jwt_decode from 'jwt-decode';
   .... 
    try {
      let token: string = state.access;  // Not necessary, just here to prove the type is correct
      let decoded: any = jwt_decode(token, { header: true });
      if (Date.now() >= decoded.exp * 1000) {
        return put(logoutAction.success(null));
      }
      setToken(state.access);
      yield put(fetchLoginAction.success(state));
    } catch (e) {
      console.log(e);
    }
```

When using Google Chrome debugger, once I reach the `jwt_decode` call, the debugger jumps out of the current function. (without going into the `catch` block). 

Then I tried to dig into the `jwt_decode` call and this is what I got from the debugger:

![Screenshot 2020-09-08 at 16 02 02](https://user-images.githubusercontent.com/5583672/92487239-49726b80-f1ed-11ea-8af9-91681c4ad2a0.png)

### Environment
I am using Typescript 3.2.2 and these libraries:
- "jwt-decode" ^2.2.0
- "@types/jwt-decode" ^2.2.1

**Comment by Sambego** [comment]
Could you try to see if you still get this error when upgrading to `v3.0.0-beta.1`? That includes an ESM build that might player nicer with your webpack setup.

**Comment by AlBlanc** [comment]
`Module not found: Can't resolve 'jwt-decode' in "....."`

**Comment by Sambego** [comment]
Oops, I made an error in the package.json, `v3.0.0-beta.2` should fix that :)

**Comment by AlBlanc** [comment]
Neither :/

**Comment by Sambego** [comment]
Here's a link to a React/Typescript project on codesandbox, it seems to be working fine with the latest beta version. https://codesandbox.io/s/keen-keldysh-r93nn?file=/src/App.tsx

Can you provide some more information so we can figure out what's going wrong?

**Comment by Sambego** [comment]
I'm closing this because there has not been a response to my latest comment. 
Feel free to leave a comment if your issue still has not been resolved and I'll re-open this issue.
