### ISSUE TITLE
"beta" version is marked as "latest"

### ISSUE THREAD

**Issue by medikoo** [auth0/jwt-decode#95]
On npm `3.0.0-beta.2` is marked as _latest_. Is this intended?

Beta by definition is not _stable_, while _latest_ by convention should point latest _stable_ version.

Is it recommended for production use to rely on _beta_ (if so, then why it's not released as _stable_?), or should we stick to v2 (then issue is, that it's not tagged as _latest_)

**Comment by Sambego** [comment]
The stable version `v3.0.0` has been released. 

This adds an ESM build for native JS imports.
**Make sure you check your import statement when upgrading.**
```javascript
import * as jwt_decode from 'jwt-decode';
```
changed to
```javascript
import jwt_decode from 'jwt-decode';
```
