### ISSUE TITLE
Error using 3.0.0-beta.2 in VueJS

### ISSUE THREAD

**Issue by sduncan-tribe** [auth0/jwt-decode#96]
Version - 3.0.0-beta.2
Enviroment - Nuxt 2.0.0 - Vuex namespace mutation

Code -  var decoded = jwt_decode(user.token);
Error - TypeError: jwt_decode__WEBPACK_IMPORTED_MODULE_5__ is not a function

I recently created a copy of some code that was working fine with version 2. Installed the latest version 3 from npm and got the error above. Reverting back to version 2.2.0 resolved the problem.

**Comment by tangjienan** [comment]
I have the same error message in Angular 7

**Comment by qpooqp** [comment]
Same for me in Angular 10.

Installed via npm.
Imported like this:
`import * as jwtDecode from 'jwt-decode';`

**Comment by Sambego** [comment]
Thanks for reporting this.

I think I need to update the docs to make this clearer, but when using a modern build system that can handle ES modules, the library should be imported as followed:
```
import jwt_decode from "jwt-decode";
```

Importing it using `import * as jwt_decode from "jwt-decode"` was a work-around to import CommonJS modules.

Here's an example using the library with Vue https://codesandbox.io/s/laughing-snow-zg457?file=/src/components/HelloWorld.vue

Let me know if this fixes your issue!

**Comment by khalilou88** [comment]
thanks, changing the import fixed the error for me in an angular 10 app

**Comment by Sambego** [comment]
The latest stable version `v3.0.0` has been released.
I'm closing this issue as there has not been a response to my latest comment from the original author.
Feel free to leave a comment if your issue has not been resolved by my above comment, and I'll re-open this issue.
